before:
  hooks:
    - go mod tidy
    - go mod download
builds:
  - main: ./cmd/aqua
    binary: aqua
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    #   - darwin
    # goarch:
    #   - amd64
    #   - arm64

changelog:
  skip: true
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

archives:
  - name_template: "{{ .Os }}_{{ .Arch }}_v{{ .Version }}"

release:
  prerelease: auto
  github:
    owner: guyb1
    name: public-plugin-repo
